"""Downstream blast-radius tracing via dbt manifest."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

import networkx as nx

_SEVERITY: dict[int, str] = {1: "critical", 2: "high", 3: "medium"}


@dataclass
class BlastRadiusNode:
    node_type: str       # model | exposure | source
    name: str
    severity: str        # critical | high | medium | low
    owner: str | None = None
    references_column: bool = False  # True when changed_column appears in node SQL


@dataclass
class BlastRadius:
    source_table: str
    changed_column: str
    nodes: list[BlastRadiusNode] = field(default_factory=list)
    edges: list[tuple[str, str]] = field(default_factory=list)  # (from_name, to_name)

    def as_summary(self) -> str:
        if not self.nodes:
            return f"No downstream dependencies for {self.source_table}.{self.changed_column}"
        lines = [f"Blast radius for {self.source_table}.{self.changed_column}:"]
        for n in self.nodes:
            col_flag = " [references column]" if n.references_column else ""
            owner_str = f" (owner: {n.owner})" if n.owner else ""
            lines.append(f"  [{n.severity.upper()}] {n.node_type}: {n.name}{owner_str}{col_flag}")
        return "\n".join(lines)


class LineageGraph:
    """Parses a dbt manifest.json and answers blast-radius queries.

    Accepts any standard dbt manifest (v9+). In production, point this at
    the customer's actual manifest.json generated by `dbt compile` or `dbt docs generate`.
    In tests and the demo, a structurally-identical fixture is used — see
    backend/tests/fixtures/manifest.json and docs/lineage.md.
    """

    def __init__(self, manifest_path: str) -> None:
        self._manifest_path = manifest_path
        self._graph: nx.DiGraph | None = None
        self._nodes: dict[str, dict[str, Any]] = {}

    def load(self) -> None:
        """Parse manifest.json and build a directed dependency graph.

        Edges run upstream → downstream, matching dbt's depends_on.nodes direction.
        Sources, models, and exposures are all treated as graph nodes.
        """
        with open(self._manifest_path, encoding="utf-8") as fh:
            manifest = json.load(fh)

        self._nodes = {}
        self._nodes.update(manifest.get("nodes", {}))
        self._nodes.update(manifest.get("sources", {}))
        self._nodes.update(manifest.get("exposures", {}))

        self._graph = nx.DiGraph()
        for uid in self._nodes:
            self._graph.add_node(uid)

        for uid, node in self._nodes.items():
            for upstream_uid in node.get("depends_on", {}).get("nodes", []):
                if upstream_uid in self._graph:
                    self._graph.add_edge(upstream_uid, uid)

    def blast_radius(self, source_table: str, changed_column: str = "") -> BlastRadius:
        """Return ordered downstream impact for a changed source table/column.

        Args:
            source_table: Table name or 'schema.table' (e.g. 'deal_pipeline_stage'
                          or 'hubspot.deal_pipeline_stage').
            changed_column: Column whose value changed (e.g. 'label'). Used to flag
                            which downstream models directly reference it in SQL.

        Returns:
            BlastRadius with nodes ordered nearest-first. Severity degrades by hop:
            hop 1 = critical, 2 = high, 3 = medium, 4+ = low.
        """
        if self._graph is None:
            raise RuntimeError("Call load() before blast_radius()")

        source_uid = self._find_source(source_table)
        if not source_uid:
            return BlastRadius(source_table=source_table, changed_column=changed_column)

        distances = nx.single_source_shortest_path_length(self._graph, source_uid)
        result: list[BlastRadiusNode] = []

        for uid, distance in sorted(distances.items(), key=lambda kv: kv[1]):
            if uid == source_uid:
                continue

            node = self._nodes[uid]
            resource_type = node.get("resource_type", "model")
            name = node.get("name", uid)
            severity = _SEVERITY.get(distance, "low")

            owner: str | None = None
            if resource_type == "exposure":
                owner_info = node.get("owner", {})
                owner = owner_info.get("name") or owner_info.get("email")

            references_column = False
            if changed_column:
                sql = node.get("raw_code") or node.get("raw_sql") or node.get("compiled_code") or ""
                references_column = changed_column in sql

            result.append(BlastRadiusNode(
                node_type=resource_type,
                name=name,
                severity=severity,
                owner=owner,
                references_column=references_column,
            ))

        # Extract edges within the blast radius subgraph (source + all downstream)
        uid_to_name: dict[str, str] = {
            source_uid: self._nodes[source_uid].get("name", source_uid)
        }
        for uid in distances:
            if uid != source_uid:
                uid_to_name[uid] = self._nodes[uid].get("name", uid)
        all_uids = set(uid_to_name)
        edges = [
            (uid_to_name[u], uid_to_name[v])
            for u, v in self._graph.edges()
            if u in all_uids and v in all_uids
        ]

        return BlastRadius(
            source_table=source_table,
            changed_column=changed_column,
            nodes=result,
            edges=edges,
        )

    def _find_source(self, source_table: str) -> str | None:
        """Match a source node by table name or 'source_name.table_name'."""
        for uid, node in self._nodes.items():
            if node.get("resource_type") != "source":
                continue
            name = node.get("name", "")
            source_name = node.get("source_name", "")
            if name == source_table or f"{source_name}.{name}" == source_table:
                return uid
        return None
